import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import Header from "@/components/Header";
import Hero from "@/components/Hero";

const geist = Geist({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geist.className} ${geistMono.className}`}>\
        <Header/>
        <Hero/> 
        {children}
        <Footer />
      </body>
    </html> 
  );
}
